[versions]
ask-exceptions-core-v = "1.0.3"
reactor-version = "3.8.7"
freefair-lombok = "9.5.0"

[libraries]
ask-exception-core = { group = "com.github.Ask-Library", name = "ask-exception-core", version.ref = "ask-exceptions-core-v" }
project-reactor = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactor-version" }

junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
project-reactor-test = { group = "io.projectreactor", name = "reactor-test", version.ref = "reactor-version" }

[plugins]
java-library = { id = "java-library" }
maven-publish = { id = "maven-publish" }
jacoco = { id = "jacoco" }
freefair-lombok = { id = "io.freefair.lombok", version.ref = "freefair-lombok" }