[versions]
springBoot = "4.0.6"
ask-exceptions-core-v = "v1.0.0"
freefair-lombok = "9.5.0"

[libraries]
spring-boot-dependencies = { group = "org.springframework.boot", name = "spring-boot-dependencies", version.ref = "springBoot" }
ask-exception-core = { group = "com.github.Ask-Library", name = "ask-exception-core", version.ref = "ask-exceptions-core-v" }
project-reactor = { group = "io.projectreactor", name = "reactor-core" }

spring-beans = { group = "org.springframework", name = "spring-beans" }

junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
project-reactor-test = { group = "io.projectreactor", name = "reactor-test" }

[plugins]
java-library = { id = "java-library" }
maven-publish = { id = "maven-publish" }
jacoco = { id = "jacoco" }
freefair-lombok = { id = "io.freefair.lombok", version.ref = "freefair-lombok" }